services:
  - type: web
    name: mojitap-flask-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
runtime: python
pythonVersion: "3.11.10"
